ARG NOTEBOOK_VERSION
FROM --platform=$TARGETPLATFORM hsz1273327/data-analyse-notebook:notebook-$NOTEBOOK_VERSION as base
RUN conda install --channel conda-forge ta-lib
# 安装需要的库
RUN pip --no-cache-dir install akshare