ARG JETPACKR_VERSION
ARG PTH_VERSION

sudo docker run -it nvcr.io/nvidia/l4t-ml:r32.7.1-py3 /bin/sh

sudo docker run -it nvcr.io/nvidia/l4t-pytorch:r32.7.1-pth1.10-py3 /bin/sh

sudo docker run -it nvcr.io/nvidia/l4t-tensorflow:r32.7.1-tf2.7-py3 /bin/sh