ARG JETPACKR_VERSION
ARG PTH_VERSION

wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null

sudo docker run -it nvcr.io/nvidia/l4t-ml:r32.7.1-py3 /bin/sh

sudo docker run -it nvcr.io/nvidia/l4t-pytorch:r32.7.1-pth1.10-py3 /bin/sh

sudo docker run -it nvcr.io/nvidia/l4t-tensorflow:r32.7.1-tf2.7-py3 /bin/sh

apt-key adv --keyserver keyserver.apt.kitware.com --recv-keys 42D5A192B819C5DA