ARG OWNER=hsz1273327
ARG CUDA_VERSION
ARG CUDNN_VERSION
ARG UBUNTU_VERSION
ARG NOTEBOOK_VERSION

ARG BASE_CONTAINER=${OWNER}/gpu-base-notebook:cuda${CUDA_VERSION}-cudnn${CUDNN_VERSION}-ubuntu${UBUNTU_VERSION}-notebook${NOTEBOOK_VERSION}
FROM --platform=$TARGETPLATFORM $BASE_CONTAINER

ARG TENSORFLOW_VERSION
ENV TENSORFLOW_VERSION=${TENSORFLOW_VERSION}

# RUN pip --no-cache-dir install nvidia-pyindex
# RUN pip --no-cache-dir install nvidia-cudnn-cu${CU} tensorflow==$TENSORFLOW_VERSION
# RUN mkdir -p $CONDA_DIR/etc/conda/activate.d
# RUN echo 'CUDNN_PATH=$(dirname $(python -c "import nvidia.cudnn;print(nvidia.cudnn.__file__)"))' >> $CONDA_DIR/etc/conda/activate.d/env_vars.sh
# RUN echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_DIR/lib/:$CUDNN_PATH/lib' >> $CONDA_DIR/etc/conda/activate.d/env_vars.sh
# RUN source $CONDA_DIR/etc/conda/activate.d/env_vars.sh

RUN pip --no-cache-dir install tensorflow==$TENSORFLOW_VERSION
RUN pip --no-cache-dir install transformers

RUN mamba install --channel conda-forge fastparquet pyarrow fastavro pygraphviz pydot lxml cython Pillow

RUN pip --no-cache-dir install --upgrade pip
RUN pip --no-cache-dir install ipywidgets
RUN pip --no-cache-dir install widgetsnbextension
RUN pip --no-cache-dir install python-snappy
RUN pip --no-cache-dir install lz4
RUN pip --no-cache-dir install boto3
RUN pip --no-cache-dir install s3fs
RUN pip --no-cache-dir install psycopg2-binary
RUN pip --no-cache-dir install peewee
RUN pip --no-cache-dir install SQLAlchemy
RUN pip --no-cache-dir install matplotlib
RUN pip --no-cache-dir install seaborn

RUN pip --no-cache-dir install pandas
RUN pip --no-cache-dir install thefuzz
RUN pip --no-cache-dir install pyod
RUN pip --no-cache-dir install scipy
RUN pip --no-cache-dir install scikit-learn
RUN pip --no-cache-dir install scikit-image
RUN pip --no-cache-dir install opencv-python

# COPY tf.ipynb /home/jovyan/work/examples/tf.ipynb