ARG OWNER=hsz1273327
ARG CUDA_VERSION
ARG CUDNN_VERSION
ARG UBUNTU_VERSION
ARG NOTEBOOK_VERSION

ARG BASE_CONTAINER=${OWNER}/gpu-base-notebook:cuda${CUDA_VERSION}-cudnn${CUDNN_VERSION}-ubuntu${UBUNTU_VERSION}-notebook${NOTEBOOK_VERSION}
FROM --platform=$TARGETPLATFORM $BASE_CONTAINER
ARG PYTORCH_VERSION
ARG CU
ENV PYTORCH_VERSION=${PYTORCH_VERSION}
ENV CU=${CU}
RUN pip install --no-cache-dir torch==$PYTORCH_VERSION torchvision torchaudio --index-url https://download.pytorch.org/whl/cu$CU

RUN mamba install --channel conda-forge fastparquet pyarrow fastavro pygraphviz pydot lxml cython Pillow

RUN pip --no-cache-dir install --upgrade pip
RUN pip --no-cache-dir install ipywidgets
RUN pip --no-cache-dir install widgetsnbextension
RUN pip --no-cache-dir install python-snappy
RUN pip --no-cache-dir install lz4
RUN pip --no-cache-dir install boto3
RUN pip --no-cache-dir install s3fs
RUN pip --no-cache-dir install psycopg2-binary
RUN pip --no-cache-dir install peewee
RUN pip --no-cache-dir install SQLAlchemy
RUN pip --no-cache-dir install matplotlib
RUN pip --no-cache-dir install seaborn

RUN pip --no-cache-dir install pandas
RUN pip --no-cache-dir install thefuzz
RUN pip --no-cache-dir install pyod
RUN pip --no-cache-dir install scipy
RUN pip --no-cache-dir install scikit-learn
RUN pip --no-cache-dir install scikit-image
RUN pip --no-cache-dir install opencv-python


# COPY torch.ipynb /home/jovyan/work/examples/torch.ipynb