ARG OWNER=hsz1273327
ARG CUDA_VERSION
ARG CUDNN_VERSION
ARG UBUNTU_VERSION
ARG NOTEBOOK_VERSION
ARG PYTORCH_VERSION
ARG CU
ARG BASE_CONTAINER=${OWNER}/base-notebook-cuda:cuda${CUDA_VERSION}-cudnn${CUDNN_VERSION}-ubuntu${UBUNTU_VERSION}-notebook${NOTEBOOK_VERSION}
FROM --platform=$TARGETPLATFORM $BASE_CONTAINER

ENV PYTORCH_VERSION=${PYTORCH_VERSION}
ENV CU=${CU}
RUN pip install torch==$PYTORCH_VERSION torchvision torchaudio --index-url https://download.pytorch.org/whl/cu$CU
# RUN mamba install --channel conda-forge pygraphviz pydot lxml cython
# RUN pip --no-cache-dir install --upgrade pip
# RUN pip --no-cache-dir install ipywidgets
# RUN pip --no-cache-dir install widgetsnbextension
# RUN pip --no-cache-dir install matplotlib
# RUN pip --no-cache-dir install seaborn

# RUN pip --no-cache-dir install pandas
# RUN pip --no-cache-dir install pyarrow
# RUN pip --no-cache-dir install thefuzz
# RUN pip --no-cache-dir install pyod
# RUN pip --no-cache-dir install scipy
# RUN pip --no-cache-dir install scikit-learn
# RUN pip --no-cache-dir install scikit-image
# RUN pip --no-cache-dir install skforecast
# RUN pip --no-cache-dir install sympy
# RUN pip --no-cache-dir install statsmodels
# RUN pip --no-cache-dir install pingouin
# RUN pip --no-cache-dir install mpmath
# RUN pip --no-cache-dir install networkx


# COPY torch.ipynb /home/jovyan/work/examples/torch.ipynb