name: "build images for cpu based notebook"

on:
  workflow_dispatch:
    inputs:
      notebook_version:
          description: 'jupyterhub version'
          required: false
          default: '6.5.4'
jobs:
  docker-build-notebook-for-small-dataset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=hsz1273327/small-dataset-notebook
          SHORTREF=${GITHUB_SHA::8}
          TAGS="${DOCKER_IMAGE}:notebook-${{ inputs.notebook_version }},${DOCKER_IMAGE}:${SHORTREF},${DOCKER_IMAGE}:latest"
          # Set output parameters.
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: "{{defaultContext}}:cpubase-notebook/for-small-dataset"
          file: dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: NOTEBOOK_VERSION=${{ inputs.notebook_version }}
          tags: ${{ steps.prep.outputs.tags }}
