name: "build images for jupyter hub"

on:
  workflow_dispatch:
    inputs:
      jupyterhub_version:
          description: 'jupyterhub version'
          required: false
          default: '4.0.1'
jobs:
  docker-build-hub-for-standalonel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=hsz1273327/jupyterhub-for-standalone
          SHORTREF=${GITHUB_SHA::8}
          TAGS="${DOCKER_IMAGE}:${{ inputs.jupyterhub_version }},${DOCKER_IMAGE}:${SHORTREF},${DOCKER_IMAGE}:latest"
          # Set output parameters.
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./hub/for-standalone
          file: dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.prep.outputs.tags }}
