name: "build images for jetson based notebook"

on:
  workflow_dispatch:
    inputs:
      jetpackR__version:
        description: "jetpack r version"
        required: false
        default: "32.7.1"
      notebook_version:
        description: 'notebook version'
        required: false
        default: '6.5.4'
      jupyterhub_version:
        description: 'jupyterhub version'
        required: false
        default: '4.0.1'
      jupyterlab_version:
        description: 'jupyterlab version'
        required: false
        default: '4.0.3'
      pth_version:
        description: 'pytorch version'
        required: false
        default: '1.10'
      tf_version:
        description: 'tensorflow version'
        required: false
        default: '2.7'
jobs:
  docker-build-torch-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: true
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=hsz1273327/jetson-torch-notebook
          SHORTREF=${GITHUB_SHA::8}
          TAGS="${DOCKER_IMAGE}:r${{ inputs.jetpackR__version }}-pth${{ inputs.pth_version }}-notebook${{ inputs.notebook_version }},${DOCKER_IMAGE}:${SHORTREF},${DOCKER_IMAGE}:latest"
          # Set output parameters.
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: "{{defaultContext}}:jetsonbase-notebook/torch-notebook"
          file: dockerfile
          platforms: linux/arm64
          push: true
          build-args: |
            JETPACKR_VERSION=${{ inputs.jetpackR__version }}
            PTH_VERSION=${{ inputs.pth_version }}
            NOTEBOOK_VERSION=${{ inputs.notebook_version }}
            JUPYTERHUB_VERSION=${{ inputs.jupyterhub_version }}
            JUPYTERLAB_VERSION=${{ inputs.jupyterlab_version}}
          tags: ${{ steps.prep.outputs.tags }}

  docker-build-tf-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: true
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=hsz1273327/jetson-tf-notebook
          SHORTREF=${GITHUB_SHA::8}
          TAGS="${DOCKER_IMAGE}:r${{ inputs.jetpackR__version }}-tf${{ inputs.tf_version }}-notebook${{ inputs.notebook_version }},,${DOCKER_IMAGE}:${SHORTREF},${DOCKER_IMAGE}:latest"
          # Set output parameters.
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: "{{defaultContext}}:jetsonbase-notebook/tf-notebook"
          file: dockerfile
          platforms: linux/arm64
          push: true
          build-args: |
            JETPACKR_VERSION=${{ inputs.jetpackR__version }}
            TF_VERSION=${{ inputs.tf_version }}
            NOTEBOOK_VERSION=${{ inputs.notebook_version }}
            JUPYTERHUB_VERSION=${{ inputs.jupyterhub_version }}
            JUPYTERLAB_VERSION=${{ inputs.jupyterlab_version}}
          tags: ${{ steps.prep.outputs.tags }}

