name: "test build images for gpu based notebook"

on:
  workflow_dispatch:
    inputs:
      cuda_version:
        description: "cuda version"
        required: false
        default: "11.8.0"
      cudnn_version:
        description: "cudnn version"
        required: false
        default: "8"
      ubuntu_version:
        description: "ubuntu version"
        required: false
        default: "22.04"
      notebook_version:
        description: 'notebook version'
        required: false
        default: '6.5.4'
      jupyterhub_version:
        description: 'jupyterhub version'
        required: false
        default: '4.0.1'
      jupyterlab_version:
        description: 'jupyterlab version'
        required: false
        default: '4.0.2'
      pytorch_version:
        description: 'pytorch version'
        required: false
        default: '2.0.1'
      tensorflow_version:
        description: 'tensorflow version'
        required: false
        default: '2.13.0'
jobs:
  docker-build-torch-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ inputs.cuda_version }}
          separator: '.'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=hsz1273327/gpu-torch-notebook
          SHORTREF=${GITHUB_SHA::8}
          TAGS="${DOCKER_IMAGE}:pytorch${{ inputs.pytorch_version }}-cuda${{ inputs.cuda_version }}-notebook${{ inputs.notebook_version }},${DOCKER_IMAGE}:${SHORTREF},${DOCKER_IMAGE}:latest"
          CU="${{steps.split.outputs._0}}${{ steps.split.outputs._1 }}"
          # Set output parameters.
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
          echo ::set-output name=cu::${CU}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: "{{defaultContext}}:gpubase-notebook/torch-notebook"
          file: dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            CUDA_VERSION=${{ inputs.cuda_version }}
            CUDNN_VERSION=${{ inputs.cudnn_version }}
            UBUNTU_VERSION=${{ inputs.ubuntu_version }}
            NOTEBOOK_VERSION=${{ inputs.notebook_version }}
            PYTORCH_VERSION=${{ inputs.pytorch_version }}
            CU=${{ steps.prep.outputs.cu }}
          tags: ${{ steps.prep.outputs.tags }}

  docker-build-tf-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ inputs.cuda_version }}
          separator: '.'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=hsz1273327/gpu-tf-notebook
          SHORTREF=${GITHUB_SHA::8}
          TAGS="${DOCKER_IMAGE}:tf${{ inputs.tensorflow_version }}-cuda${{ inputs.cuda_version }}-notebook${{ inputs.notebook_version }},${DOCKER_IMAGE}:${SHORTREF},${DOCKER_IMAGE}:latest"
          CU="${{steps.split.outputs._0}}"
          # Set output parameters.
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
          echo ::set-output name=cu::${CU}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: "{{defaultContext}}:gpubase-notebook/tf-notebook"
          file: dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            CUDA_VERSION=${{ inputs.cuda_version }}
            CUDNN_VERSION=${{ inputs.cudnn_version }}
            UBUNTU_VERSION=${{ inputs.ubuntu_version }}
            NOTEBOOK_VERSION=${{ inputs.notebook_version }}
            TENSORFLOW_VERSION=${{ inputs.tensorflow_version }}
          tags: ${{ steps.prep.outputs.tags }}