ARG NOTEBOOK_VERSION
FROM --platform=$TARGETPLATFORM hsz1273327/data-analyse-notebook:notebook-$NOTEBOOK_VERSION as base
# 安装需要的库
RUN conda install --channel conda-forge dask
RUN pip install --no-cache-dir clickhouse-connect

# 安装需要的库
RUN conda install --channel conda-forge Pillow
RUN pip --no-cache-dir install scikit-image
RUN pip --no-cache-dir install opencv-python

# # 复制例子
# COPY conntodata.ipynb /home/jovyan/work/examples/conntodata.ipynb